name: TimedBroadcast
main: lexteam.timedbroadcast.TimedBroadcast
version: ${version}
commands:
  enabletb:
    description: Enabled TimedBroadcast.
    usage: "Usage: '/enabletb' to enable TimedBroadcast"
    aliases: tbe
  disabletb:
    description: Disables TimedBroadcast.
    usage: "Usage: '/disabletb' to disable TimedBroadcast"
    aliases: tbd
permissions:
	timedbroadcast.*:
		description: Gives access to all TimedBroadcast commands.
		children:
			timedbroadcast.enable: true
	timedbroadcast.both:
		description: Enable and disable TimedBroadcast.
		default: op
	timedbroadcast.enable:
		description: Enable TimedBroadcast.
		default: op
	timedbroadcast.disable:
		description: Disable TimedBroadcast.
		default: op