name: TimedBroadcast
main: lexteam.timedbroadcast.TimedBroadcast
version: ${version}
commands:
  enabletb:
    description: Enabled TimedBroadcast.
    usage: "Usage: '/enabletb' to enable TimedBroadcast"
    aliases: tbe
  disabletb:
    description: Disables TimedBroadcast.
    usage: "Usage: '/disabletb' to disable TimedBroadcast"
    aliases: tbd