name: TimedBroadcast
main: lexteam.timedbroadcast.TimedBroadcast
version: ${version}
commands:
  timedbroadcast:
    description: Command for TimedBroadcast.
    usage: "Usage: '/timedbroadcast' to access TimedBroadcast related commands"
    aliases: tb
permissions:
	timedbroadcast.*:
		description: Gives access to all TimedBroadcast commands.
		children:
			timedbroadcast.both: true
			timedbroadcast.add: true
			timedbroadcast.removeall: true
	timedbroadcast.both:
		description: Enable and disable TimedBroadcast.
		default: op
	timedbroadcast.enable:
		description: Enable TimedBroadcast.
		default: op
	timedbroadcast.disable:
		description: Disable TimedBroadcast.
		default: op
	timedbroadcast.add:
		description: Adds a phrase to the broadcast list.
		default: op
	timedbroadcast.removeall:
		description: Removes all phrases in the broadcast list.
		default: op